#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Test

on:
  push:
    branches: [master]
  schedule:
    # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
    - cron: "0 5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      SHA: ${{ github.sha }}

    steps:
      - name: Checkout Camel project
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch ${{ env.BRANCH_NAME }}-${{ env.SHA }}; echo "MY_DATE=$(date +'%Y-%m-%dT-%H-%M-%S')" >> $GITHUB_ENV

      - name: info
        run: ls ./

      - name: Add Test file
        run: echo ${{ env.MY_DATE }}-${{ env.BRANCH_NAME }}-${{ env.SHA }} > info.txt

      - name: info2
        run: ls ./

      - name: Apply Changes
        uses: EndBug/add-and-commit@v9.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
          new_branch: ${{ env.BRANCH_NAME }}-${{ env.MY_DATE }}
          add: 'info.txt'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master-2022-09-08T-17-30-38
          base: ${{ env.BRANCH_NAME }}
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
