name: mysql2

on:
  pull_request:
    branches: [master,dev-*]
  push:
    branches: [master,dev-*]

jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          ls
          config="--host 127.0.0.1 --port 32574 -uroot -ppassword "
          MYSQL_DB=linkis_test
          mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "SHOW DATABASES"
          mysql --host 127.0.0.1 --port 32574 -uroot -ppassword  --default-character-set=utf8 -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;"
          mysql $config  -D$MYSQL_DB --default-character-set=utf8 -e "source ./db/linkis_ddl.sql"
          mysql $config  -D$MYSQL_DB --default-character-set=utf8 -e "source ./db/linkis_dml.sql"
          mysql $config  -D$MYSQL_DB -e "show tables"
          mysql $config  -D$MYSQL_DB -e "select * from linkis_test.linkis_ps_configuration_config_key"


